version: '3.9'

services:
  main:
    build:
      context: .
      target: development
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/usr/src/app/src
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev
    depends_on:
      - redis
    networks:
      - facebooks
    links:
      - redis
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - facebooks

volumes:
  mongo-data:
networks:
  - facebooks
